import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { sailDesignSystem, getButtonClasses } from "@/config/sailDesignSystem";

const tokens = sailDesignSystem.colors;
const buttonClasses = getButtonClasses();
const cardStyle = { backgroundColor: tokens.cardBackground, borderColor: tokens.border, borderRadius: sailDesignSystem.components.card.borderRadius, boxShadow: sailDesignSystem.components.card.shadow };
const sectionStyle = { backgroundColor: tokens.tableHeader, borderColor: tokens.border };
const labelStyle = { color: tokens.textSecondary, fontSize: sailDesignSystem.typography.fontSize.xs };
const valueStyle = { color: tokens.textPrimary, fontSize: sailDesignSystem.typography.fontSize.sm };
const read = (value: unknown) => value == null || value === "" ? "—" : String(value);
const date = (value: unknown) => { if (!value) return "—"; const parsed = new Date(String(value)); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }).replace(/ /g, "-"); };
function Header({ part, subtitle, completed }: { part: "A" | "C"; subtitle: string; completed: boolean }) {
  return <header className="mb-6 border-b pb-4" style={{ borderColor: tokens.headerText }}><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold" style={{ color: tokens.headerText }}>Part {part}: {part === "A" ? "Basic Information" : "Office Review"}</h2><p className="mt-1 text-sm" style={{ color: tokens.textSecondary }}>{subtitle}</p></div>{completed && <span className="text-xs font-semibold" style={{ color: tokens.success }}>Completed</span>}</div><div className="mt-3 h-0.5 w-full" style={{ backgroundColor: tokens.headerText }}/></header>;
}
function Field({ label, value, testId }: { label: string; value: unknown; testId?: string }) {
  return <div className="rounded-md border px-3 py-2" style={sectionStyle} data-testid={testId}><label className="block font-medium" style={labelStyle}>{label}</label><p className="mt-1" style={valueStyle}>{read(value)}</p></div>;
}
export function InterviewPartA({ submissionUuid, data, completed, onSaved }: { submissionUuid: string; data?: any; completed: boolean; onSaved?: () => void }) {
  const [draft, setDraft] = useState({ category: data?.interview_category || "", stage: data?.interview_stage || "" }); const [saving, setSaving] = useState(false); const { toast } = useToast();
  useEffect(() => setDraft({ category: data?.interview_category || "", stage: data?.interview_stage || "" }), [data]);
  const save = async () => { setSaving(true); try { await apiRequest("PUT", `/api/v2/interviews/submissions/${submissionUuid}/part-a`, { interviewCategory: draft.category || null, interviewStage: draft.stage || null }); onSaved?.(); toast({ title: "Part A saved", description: "Interview classification has been recorded." }); } catch (error) { toast({ title: "Part A could not be saved", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setSaving(false); } };
  return <section className="rounded-lg border p-6" style={cardStyle} data-testid="interview-part-a"><Header part="A" subtitle="B6 context is authoritative and read-only." completed={completed}/><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Candidate" value={data?.candidate_name} testId="interview-part-a-candidate"/><Field label="Rank applied for" value={data?.rank} testId="interview-part-a-rank"/><Field label="Nationality" value={data?.nationality} testId="interview-part-a-nationality"/><Field label="Interview date" value={date(data?.interview_date)} testId="interview-part-a-date"/><Field label="Interviewer" value={data?.interviewer_name} testId="interview-part-a-interviewer"/><label className="block font-medium" style={labelStyle}>Interview category<Input data-testid="input-interview-category" disabled={completed} value={draft.category} onChange={e => setDraft(v => ({ ...v, category: e.target.value }))} className="mt-1" placeholder="Category"/></label><label className="block font-medium" style={labelStyle}>Interview stage<Input data-testid="input-interview-stage" disabled={completed} value={draft.stage} onChange={e => setDraft(v => ({ ...v, stage: e.target.value }))} className="mt-1" placeholder="Stage"/></label></div>{!completed && <div className="mt-6 flex justify-end"><Button data-testid="button-save-interview-part-a" size="sm" className={buttonClasses.primary} onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save Part A"}</Button></div>}</section>;
}
export function InterviewPartC({ submissionUuid, data, completed, onSaved }: { submissionUuid: string; data?: any; completed: boolean; onSaved?: () => void }) {
  const [comments, setComments] = useState(data?.interviewer_comments || ""); const [saving, setSaving] = useState(false); const { toast } = useToast(); useEffect(() => setComments(data?.interviewer_comments || ""), [data]);
  const save = async () => { setSaving(true); try { await apiRequest("PUT", `/api/v2/interviews/submissions/${submissionUuid}/part-c`, { interviewerComments: comments || null }); onSaved?.(); toast({ title: "Office review saved", description: "Interview comments have been recorded." }); } catch (error) { toast({ title: "Office review could not be saved", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setSaving(false); } };
  return <section className="rounded-lg border p-6" style={cardStyle} data-testid="interview-part-c"><Header part="C" subtitle="B6 outcome is read-only; office notes are editable." completed={completed}/><div className="mb-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="B6 status" value={data?.status} testId="interview-part-c-status"/><Field label="B6 result" value={data?.result} testId="interview-part-c-result"/></div><div className="rounded-md border p-4" style={sectionStyle}><Textarea data-testid="textarea-interview-office-comments" disabled={completed} value={comments} onChange={e => setComments(e.target.value)} placeholder="Add office review comments…" rows={5} className="bg-transparent"/></div><div className="mt-4 flex items-center justify-between gap-4 text-xs" style={{ color: tokens.textSecondary }}><span data-testid="interview-office-review-audit">{data?.office_reviewed_by_name ? `Reviewed by ${data.office_reviewed_by_name}` : "Not yet reviewed"}{data?.office_reviewed_at ? ` · ${date(data.office_reviewed_at)}` : ""}</span>{!completed && <Button data-testid="button-save-interview-part-c" size="sm" className={buttonClasses.primary} onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save review"}</Button>}</div></section>;
}
export function interviewFixedParts(submissionUuid: string, data: any, completed: boolean, onSaved: () => void): Record<string, React.ReactNode> { return { A: <InterviewPartA submissionUuid={submissionUuid} data={data?.partA} completed={completed} onSaved={onSaved}/>, C: <InterviewPartC submissionUuid={submissionUuid} data={data?.partC} completed={completed} onSaved={onSaved}/> }; }