-- Crewing Test Case Manager
-- Single table holding functional/UAT test cases grouped by module.
-- Defined in shared/v2/test-cases/schema.ts. Created idempotently so fresh,
-- production, and per-tenant databases all get it.
--
-- NOTE: audit timestamp columns use TIMESTAMP (without time zone) to match the
-- Drizzle schema's timestamp(...).defaultNow().

CREATE TABLE IF NOT EXISTS test_cases_v2 (
  id SERIAL PRIMARY KEY,
  tc_uuid TEXT NOT NULL UNIQUE,
  module TEXT NOT NULL,
  reference TEXT,
  title TEXT NOT NULL,
  area_feature TEXT,
  category TEXT NOT NULL DEFAULT 'Functional',
  priority TEXT NOT NULL DEFAULT 'Medium',
  preconditions TEXT,
  steps TEXT,
  expected_result TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN DEFAULT FALSE,
  is_sync BOOLEAN DEFAULT FALSE
);

-- ============================================================
-- Starter test cases. These reflect ONLY current, working v2
-- functionality (legacy/v1, payroll/accounts, and any
-- placeholder/"coming soon" features are intentionally excluded).
-- Idempotent via fixed tc_uuid + ON CONFLICT DO NOTHING.
-- ============================================================

INSERT INTO test_cases_v2 (tc_uuid, module, reference, title, category, priority, preconditions, steps, expected_result, sort_order) VALUES

-- Crew Pool
('seed-cp-001', 'Crew Pool', 'CP-001', 'Create a new crew member profile', 'Functional', 'High',
 'User has Crew Pool create permission.',
 '1. Open Crew Pool. 2. Click Add Crew. 3. Fill mandatory personal details. 4. Save.',
 'New crew member is created and appears in the crew pool list.', 1),
('seed-cp-002', 'Crew Pool', 'CP-002', 'Edit crew personal and address details', 'Functional', 'Medium',
 'At least one crew member exists.',
 '1. Open a crew profile. 2. Edit personal/address/next-of-kin fields. 3. Save.',
 'Updated details are persisted and shown on the profile.', 2),
('seed-cp-003', 'Crew Pool', 'CP-003', 'Search and filter the crew pool', 'Functional', 'Medium',
 'Crew pool contains multiple members.',
 '1. Open Crew Pool. 2. Apply filters for rank, nationality, and status.',
 'List is filtered to matching crew members only.', 3),
('seed-cp-004', 'Crew Pool', 'CP-004', 'Manage crew documents with expiry tracking', 'Functional', 'High',
 'A crew profile is open.',
 '1. Go to Documents (travel docs, visas, licenses, courses). 2. Add a document with expiry date and attachment. 3. Save.',
 'Document is saved with attachment and expiry is tracked.', 4),
('seed-cp-005', 'Crew Pool', 'CP-005', 'Record sea service with experience calculation', 'Functional', 'Medium',
 'A crew profile is open.',
 '1. Open Sea Service. 2. Add a sea service entry (rank, vessel type, dates). 3. Save.',
 'Entry is saved and rank/company/vessel-type experience totals update.', 5),
('seed-cp-006', 'Crew Pool', 'CP-006', 'Record briefing and de-briefing sessions', 'UAT', 'Medium',
 'A crew profile is open.',
 '1. Open Briefing/De-briefing. 2. Record a session with attachment. 3. Save.',
 'Briefing and de-briefing records are saved with attachments.', 6),
('seed-cp-007', 'Crew Pool', 'CP-007', 'Terminate crew employment', 'Functional', 'Medium',
 'An active crew member exists.',
 '1. Open a crew profile. 2. Trigger employment termination. 3. Confirm.',
 'Crew record moves to the Terminated view.', 7),

-- Vessel
('seed-ve-001', 'Vessel', 'VE-001', 'View vessel manning plan', 'Functional', 'High',
 'A vessel with assigned crew exists.',
 '1. Open Vessel. 2. Select a vessel. 3. View manning (On Board, Reliever, Planned).',
 'Current manning statuses are displayed correctly per rank.', 1),
('seed-ve-002', 'Vessel', 'VE-002', 'Sign on a reliever', 'Functional', 'High',
 'A reliever is planned for a vessel.',
 '1. Open vessel planning. 2. Select the planned reliever. 3. Sign-on Reliever.',
 'Reliever transitions to active On Board status.', 2),
('seed-ve-003', 'Vessel', 'VE-003', 'Review vessel compliance matrix', 'Functional', 'Medium',
 'A vessel with crew certifications exists.',
 '1. Open the vessel compliance matrix. 2. Review mandatory certifications vs rank requirements.',
 'Compliance gaps are highlighted against rank requirements.', 3),
('seed-ve-004', 'Vessel', 'VE-004', 'Export Officer Matrix to Excel', 'Functional', 'Medium',
 'A vessel with officers exists.',
 '1. Open the vessel. 2. Choose Export Officer Matrix.',
 'An Excel file with officer experience/vetting data is downloaded.', 4),
('seed-ve-005', 'Vessel', 'VE-005', 'Export Crew List', 'Functional', 'Medium',
 'A vessel with onboard crew exists.',
 '1. Open the vessel. 2. Choose Export Crew List.',
 'A standardized crew list is generated for download.', 5),

-- Rest Hours
('seed-rh-001', 'Rest Hours', 'RH-001', 'Record daily work and rest hours', 'Functional', 'High',
 'A crew member is assigned to a vessel for the selected month.',
 '1. Open Rest Hours. 2. Select crew/month. 3. Enter hour-by-hour work/rest. 4. Save.',
 'Hours are saved and validated against STCW/MLC/OPA rules.', 1),
('seed-rh-002', 'Rest Hours', 'RH-002', 'View non-conformities dashboard', 'Functional', 'Medium',
 'Rest hour records with violations exist.',
 '1. Open the Rest Hours violations dashboard. 2. Filter by rank and violation code.',
 'Non-conformities (A-H) are summarized and filterable.', 2),
('seed-rh-003', 'Rest Hours', 'RH-003', 'Complete vessel and office review sign-off', 'UAT', 'High',
 'A month of rest-hour records is recorded for a vessel.',
 '1. Submit Vessel Review (Master). 2. Submit Office Review (Superintendent).',
 'Review statuses progress through the multi-stage sign-off.', 3),
('seed-rh-004', 'Rest Hours', 'RH-004', 'Schedule fixed and variable tasks', 'Functional', 'Medium',
 'A vessel rest-hour sheet is open.',
 '1. Add a recurring fixed task. 2. Add a one-off variable event (drill/port call). 3. Save.',
 'Tasks are scheduled and reflected on the rest-hour records.', 4),
('seed-rh-005', 'Rest Hours', 'RH-005', 'Apply dateline adjustment', 'Functional', 'Low',
 'A crew member crosses the International Date Line in the period.',
 '1. Open the daily record. 2. Apply an hour gain/loss for dateline crossing.',
 'Hours are adjusted correctly for the gained/lost time.', 5),

-- Promotions
('seed-pr-001', 'Promotions', 'PR-001', 'View promotion review board', 'Functional', 'High',
 'Eligible crew exist per the rank hierarchy.',
 '1. Open Promotions. 2. View the list of eligible crew.',
 'Eligible crew members are listed per defined hierarchy.', 1),
('seed-pr-002', 'Promotions', 'PR-002', 'Complete a promotion checklist', 'Functional', 'High',
 'A crew member is under promotion review.',
 '1. Open a promotion record. 2. Verify criteria (CES tests, training needs, appraisals). 3. Save.',
 'Checklist items are recorded against criteria master requirements.', 2),
('seed-pr-003', 'Promotions', 'PR-003', 'Progress a promotion through approval stages', 'UAT', 'High',
 'A promotion checklist is complete.',
 '1. Move record from In Progress to Awaiting Approval. 2. Approve to Promoted.',
 'Promotion status advances through the workflow stages.', 3),
('seed-pr-004', 'Promotions', 'PR-004', 'Verify criteria against appraisals and training', 'Functional', 'Medium',
 'Crew has appraisal and training history.',
 '1. Open promotion criteria verification. 2. Check appraisal recommendation and mandatory training.',
 'Criteria reflect linked appraisal recommendations and training completion.', 4),

-- Appraisals
('seed-ap-001', 'Appraisals', 'AP-001', 'Complete the vessel appraisal (Part A/B)', 'Functional', 'High',
 'A crew member is due for appraisal.',
 '1. Open Appraisals. 2. Complete Part A/B on the vessel. 3. Submit.',
 'Vessel stage is saved and routed to the next stage.', 1),
('seed-ap-002', 'Appraisals', 'AP-002', 'Score competence assessment', 'Functional', 'High',
 'An appraisal is in progress.',
 '1. Open the competence section. 2. Score professional, leadership and behavioral items. 3. Save.',
 'Competence scores are saved on the appraisal.', 2),
('seed-ap-003', 'Appraisals', 'AP-003', 'Identify training needs during appraisal', 'Functional', 'Medium',
 'An appraisal is in progress.',
 '1. Flag a training need within the appraisal. 2. Save.',
 'Training need is recorded and feeds the training matrix.', 3),
('seed-ap-004', 'Appraisals', 'AP-004', 'Set promotion recommendation', 'UAT', 'Medium',
 'An appraisal is being finalized.',
 '1. Mark the appraisal as Recommended for promotion. 2. Save.',
 'Recommendation flags the crew member as eligible in Promotions.', 4),
('seed-ap-005', 'Appraisals', 'AP-005', 'Complete office appraisal stage (Part F/G)', 'Functional', 'Medium',
 'Vessel and seafarer stages are complete.',
 '1. Open the office stage. 2. Complete Part F/G. 3. Finalize.',
 'Appraisal is finalized through the office stage.', 5),

-- Drugs & Alcohol
('seed-da-001', 'Drugs & Alcohol', 'DA-001', 'Create a drug and alcohol test record', 'Functional', 'High',
 'A vessel exists.',
 '1. Open Drugs & Alcohol. 2. Add a test record (annual/monthly/periodic/post-incident). 3. Save.',
 'Test record is created and listed for the vessel.', 1),
('seed-da-002', 'Drugs & Alcohol', 'DA-002', 'Edit and delete a test record', 'Functional', 'Medium',
 'A test record exists.',
 '1. Open a test record. 2. Edit fields and save. 3. Delete the record.',
 'Edits persist and deletion removes the record from the list.', 2),
('seed-da-003', 'Drugs & Alcohol', 'DA-003', 'Track testing schedule per vessel', 'Functional', 'Medium',
 'Vessels with test records exist.',
 '1. Open the vessel testing view. 2. Review testing status and planned unannounced tests.',
 'Testing status per vessel is shown with planning details.', 3),
('seed-da-004', 'Drugs & Alcohol', 'DA-004', 'Log a violation with lab report attachment', 'UAT', 'High',
 'A test record exists.',
 '1. Open a test record. 2. Record a positive result/violation. 3. Attach the lab report. 4. Save.',
 'Violation is logged with the laboratory report attached.', 4),
('seed-da-005', 'Drugs & Alcohol', 'DA-005', 'Verify onboard crew before test selection', 'Functional', 'Medium',
 'A vessel with onboard crew exists.',
 '1. Open the test record. 2. Verify the current onboard crew list.',
 'Onboard crew list is confirmed before selecting personnel.', 5),

-- Recruitment
('seed-rc-001', 'Recruitment', 'RC-001', 'Add a candidate to the pipeline', 'Functional', 'High',
 'User has Recruitment create permission.',
 '1. Open Recruitment. 2. Add a new candidate. 3. Save.',
 'Candidate appears in the pipeline at the Applied stage.', 1),
('seed-rc-002', 'Recruitment', 'RC-002', 'Progress candidate through screening (B1-B8)', 'Functional', 'High',
 'A candidate exists in the pipeline.',
 '1. Open a candidate. 2. Complete screening steps (references, certificate verification, CES tests, interview).',
 'Screening steps are recorded and the candidate advances.', 2),
('seed-rc-003', 'Recruitment', 'RC-003', 'Complete suitability assessment', 'Functional', 'Medium',
 'A candidate is in screening.',
 '1. Open suitability assessment. 2. Check vessel types and fleet groups. 3. Save.',
 'Suitability against vessel types and fleet groups is recorded.', 3),
('seed-rc-004', 'Recruitment', 'RC-004', 'Transfer candidate to crew pool', 'UAT', 'High',
 'A candidate is Ready for Hire.',
 '1. Open the candidate. 2. Click Transfer to Crew Pool. 3. Confirm.',
 'Candidate becomes a crew record with screening data/documents migrated.', 4),

-- Rotation
('seed-ro-001', 'Rotation', 'RO-001', 'Create a rotation planning draft', 'Functional', 'High',
 'Vessels and crew exist.',
 '1. Open Rotation. 2. Create a new planning draft across vessels/ranks. 3. Save.',
 'Draft is created and editable.', 1),
('seed-ro-002', 'Rotation', 'RO-002', 'View due crew dashboard', 'Functional', 'Medium',
 'Crew with upcoming relief dates exist.',
 '1. Open the Due Crew dashboard.',
 'Crew approaching relief-due dates are listed.', 2),
('seed-ro-003', 'Rotation', 'RO-003', 'Propose crew-to-vessel assignments', 'Functional', 'Medium',
 'A rotation draft exists.',
 '1. Open a draft. 2. Propose crew assignments for approval. 3. Submit.',
 'Proposed assignments are routed for superintendent approval.', 3),
('seed-ro-004', 'Rotation', 'RO-004', 'Deploy a rotation entry', 'UAT', 'High',
 'A proposed rotation is approved.',
 '1. Open the approved proposal. 2. Deploy the rotation entry.',
 'Deployment updates the vessel planning module.', 4),

-- Admin & Masters
('seed-ad-001', 'Admin & Masters', 'AD-001', 'Manage form versions in the form builder', 'Functional', 'Medium',
 'User has Admin access.',
 '1. Open Admin. 2. Open the form builder. 3. Create/edit an appraisal or screening form version. 4. Save.',
 'Form version is saved and available for use.', 1),
('seed-ad-002', 'Admin & Masters', 'AD-002', 'Define rank hierarchy and promotion paths', 'Functional', 'Medium',
 'User has Admin access.',
 '1. Open rank hierarchy. 2. Define a promotion path (e.g., 3/OFF to 2/OFF). 3. Save.',
 'Rank hierarchy and promotion path are saved.', 2),
('seed-ad-003', 'Admin & Masters', 'AD-003', 'Configure role-based access control', 'UAT', 'High',
 'User has Admin access.',
 '1. Open Access Control. 2. Set menu and action permissions for a role. 3. Save.',
 'Permissions are saved and enforced for that role.', 3),
('seed-ad-004', 'Admin & Masters', 'AD-004', 'Manage global master data', 'Functional', 'Medium',
 'User has Admin access.',
 '1. Open Masters. 2. Add/edit a master record (port, nationality, vessel, training). 3. Save.',
 'Master data record is created/updated and available app-wide.', 4)

ON CONFLICT (tc_uuid) DO NOTHING;
