import React from "react";
import { ActivityIndicator, FlatList, Modal, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import type { MasterOption } from "../api/crewInformationApi";

export const palette = {
  navy: "#12324A",
  blue: "#1E6387",
  teal: "#159A9C",
  mist: "#EAF3F5",
  ink: "#173B50",
  muted: "#607987",
  line: "#C9DDE2",
  amber: "#C98B35",
  white: "#FBFDFC",
  red: "#B7504F",
};

export function StateView({ loading, error, retry, empty, children }: { loading?: boolean; error?: string; retry?: () => void; empty?: string; children?: React.ReactNode }) {
  if (loading) return <View style={styles.state}><View style={styles.loadingMark}><ActivityIndicator color={palette.teal} /></View><Text style={styles.stateText}>Loading your records</Text></View>;
  if (error) return <View style={styles.state}><Text style={styles.stateTitle}>We could not reach your records</Text><Text style={styles.stateText}>{error}</Text>{retry && <Button title="Try again" onPress={retry} />}</View>;
  if (empty) return <View style={styles.empty}><Text style={styles.emptyTitle}>{empty}</Text><Text style={styles.stateText}>Your information will appear here when it is added.</Text></View>;
  return <>{children}</>;
}
export function Button({ title, onPress, secondary, disabled, testID }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; testID?: string }) {
  return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, disabled && styles.disabled, pressed && styles.pressed]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{title}</Text></Pressable>;
}
export function Field({ label, value, onChangeText, keyboardType = "default", required, error, inputRef, multiline }: { label: string; value: string; onChangeText: (v: string) => void; keyboardType?: any; required?: boolean; error?: string; inputRef?: any; multiline?: boolean }) {
  return <View style={styles.field}><Text style={styles.label}>{label}{required ? "  *" : ""}</Text><TextInput ref={inputRef} accessibilityLabel={label} accessibilityHint={error || undefined} value={value} onChangeText={onChangeText} keyboardType={keyboardType} autoCapitalize={keyboardType === "email-address" ? "none" : "sentences"} multiline={multiline} placeholder="Not provided" placeholderTextColor="#738894" style={[styles.input, multiline && { minHeight: 90, textAlignVertical: "top", paddingVertical: 12 }, error && { borderColor: "#B74646", borderWidth: 2 }]} />{error ? <Text accessibilityLiveRegion="polite" style={{ color: "#B74646", fontSize: 12, marginTop: 4 }}>{error}</Text> : null}</View>;
}
export function SelectField({ label, value, options, onChange, error }: { label: string; value: string; options: MasterOption[]; onChange: (value: string) => void; error?: string }) {
  const [open, setOpen] = React.useState(false);
  const selected = options.find((option) => option.value === value);
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${label}, ${selected?.label || "not selected"}`} onPress={() => setOpen(true)} style={[styles.input, styles.select, error && { borderColor: "#B74646", borderWidth: 2 }]}><Text style={{ color: selected ? palette.ink : "#738894" }}>{selected?.label || "Choose an option"}</Text><Text style={{ color: palette.teal, fontSize: 20 }}>⌄</Text></Pressable>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}<Modal visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><SafeAreaView style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>{label}</Text><Button title="Close" secondary onPress={() => setOpen(false)} /></View><FlatList data={options} keyExtractor={(option) => option.value} renderItem={({ item }) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: item.value === value }} onPress={() => { onChange(item.value); setOpen(false); }} style={styles.option}><Text style={styles.optionText}>{item.label}</Text>{item.value === value ? <Text style={styles.selectedMark}>Selected</Text> : null}</Pressable>} ListEmptyComponent={<StateView empty="No options available" />} /></SafeAreaView></Modal></View>;
}
export function MultiSelectField({ label, values, options, onChange }: { label: string; values: string[]; options: MasterOption[]; onChange: (values: string[]) => void }) {
  const [open, setOpen] = React.useState(false);
  const labels = options.filter((option) => values.includes(option.value)).map((option) => option.label);
  const toggle = (value: string) => onChange(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${label}, ${labels.length} selected`} onPress={() => setOpen(true)} style={[styles.input, styles.select]}><Text numberOfLines={2} style={{ color: labels.length ? palette.ink : "#738894", flex: 1 }}>{labels.join(", ") || "Choose one or more"}</Text><Text style={{ color: palette.teal, fontSize: 20 }}>⌄</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><SafeAreaView style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>{label}</Text><Button title="Done" onPress={() => setOpen(false)} /></View><FlatList data={options} keyExtractor={(option) => option.value} renderItem={({ item }) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: values.includes(item.value) }} onPress={() => toggle(item.value)} style={styles.option}><Text style={styles.optionText}>{item.label}</Text><Text style={styles.selectedMark}>{values.includes(item.value) ? "Selected" : ""}</Text></Pressable>} /></SafeAreaView></Modal></View>;
}
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.mist }, content: { padding: 20, paddingBottom: 48 }, title: { fontSize: 29, fontWeight: "800", color: palette.navy, letterSpacing: -0.6 }, subtitle: { color: palette.muted, marginTop: 5, lineHeight: 20 }, card: { backgroundColor: palette.white, borderRadius: 14, padding: 17, marginTop: 12, borderWidth: 1, borderColor: palette.line, shadowColor: palette.navy, shadowOpacity: 0.04, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1 }, cardTitle: { color: palette.ink, fontWeight: "800", fontSize: 16 }, cardMeta: { color: palette.muted, marginTop: 5 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, state: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28 }, loadingMark: { width: 48, height: 48, borderRadius: 16, backgroundColor: "#D9ECEE", alignItems: "center", justifyContent: "center" }, stateTitle: { fontSize: 17, color: palette.navy, fontWeight: "800", textAlign: "center", marginBottom: 8 }, stateText: { color: palette.muted, textAlign: "center", marginTop: 8, lineHeight: 20 }, empty: { backgroundColor: palette.white, borderRadius: 14, borderWidth: 1, borderColor: palette.line, padding: 24, marginTop: 18 }, emptyTitle: { color: palette.navy, fontWeight: "800", fontSize: 16 }, button: { minHeight: 48, borderRadius: 11, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", backgroundColor: palette.teal, marginTop: 16 }, buttonText: { color: palette.white, fontWeight: "800" }, secondary: { backgroundColor: palette.white, borderWidth: 1, borderColor: palette.line }, secondaryText: { color: palette.blue }, disabled: { opacity: .5 }, pressed: { opacity: .72, transform: [{ scale: .985 }] }, field: { marginTop: 14 }, label: { color: palette.ink, fontWeight: "700", marginBottom: 6 }, input: { minHeight: 48, borderRadius: 10, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.white, paddingHorizontal: 12, color: palette.ink }, select: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 10 }, error: { color: palette.red, fontSize: 12, marginTop: 4 }, modal: { flex: 1, backgroundColor: palette.mist }, modalHeader: { paddingHorizontal: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: palette.line }, modalTitle: { fontSize: 24, fontWeight: "800", color: palette.navy, marginTop: 10 }, option: { minHeight: 54, backgroundColor: palette.white, borderBottomWidth: 1, borderBottomColor: palette.line, paddingHorizontal: 20, paddingVertical: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, optionText: { color: palette.ink, fontSize: 16, flex: 1 }, selectedMark: { color: palette.teal, fontWeight: "800", marginLeft: 12 }, sectionHeader: { color: palette.blue, fontSize: 12, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase", marginTop: 25, marginBottom: 5 },
});