export const countryDialingCodes: Record<string, string> = {
  "AFGHANISTAN": "+93",
  "ALBANIA": "+355",
  "ALGERIA": "+213",
  "AMERICAN SAMOA": "+1-684",
  "ANDORRA": "+376",
  "ANGOLA": "+244",
  "ANGUILLA": "+1-264",
  "ANTIGUA AND BARBUDA": "+1-268",
  "ARGENTINA": "+54",
  "ARMENIA": "+374",
  "ARUBA": "+297",
  "AUSTRALIA": "+61",
  "AUSTRIA": "+43",
  "AZERBAIJAN": "+994",
  "BAHAMAS": "+1-242",
  "BAHRAIN": "+973",
  "BANGLADESH": "+880",
  "BARBADOS": "+1-246",
  "BELARUS": "+375",
  "BELGIUM": "+32",
  "BELIZE": "+501",
  "BENIN": "+229",
  "BERMUDA": "+1-441",
  "BHUTAN": "+975",
  "BOLIVIA": "+591",
  "BOSNIA-HERZEGOVINA": "+387",
  "BOTSWANA": "+267",
  "BRAZIL": "+55",
  "BRITISH INDIAN OCEAN TERRITORY": "+246",
  "BRITISH VIRGIN ISLANDS": "+1-284",
  "BRUNEI DARUSSALAM": "+673",
  "BULGARIA": "+359",
  "BURKINA FASO": "+226",
  "BURUNDI": "+257",
  "CAMBODIA": "+855",
  "CAMEROON": "+237",
  "CANADA": "+1",
  "CAPE VERDE": "+238",
  "CAYMAN ISLANDS": "+1-345",
  "CENTRAL AFRICAN REPUBLIC": "+236",
  "CHAD": "+235",
  "CHILE": "+56",
  "CHINA PEO REP OF": "+86",
  "CHRISTMAS ISLANDS": "+61",
  "COCOS (KEELING) ISLANDS": "+61",
  "COLOMBIA": "+57",
  "COMOROS": "+269",
  "CONGO": "+242",
  "COOK ISLANDS": "+682",
  "COSTA RICA": "+506",
  "COTE D'IVOIRE": "+225",
  "CROATIA": "+385",
  "CUBA": "+53",
  "CYPRUS": "+357",
  "CZECH REPUBLIC": "+420",
  "DEMOCRATIC REPUBLIC OF THE CONGO": "+243",
  "DENMARK": "+45",
  "DJIBOUTI": "+253",
  "DOMINICA": "+1-767",
  "DOMINICAN REPUBLIC": "+1-809",
  "ECUADOR": "+593",
  "EGYPT": "+20",
  "EL SALVADOR": "+503",
  "EQUATORIAL GUINEA": "+240",
  "ERITREA": "+291",
  "ESTONIA": "+372",
  "ETHIOPIA": "+251",
  "FAEROE ISLANDS": "+298",
  "FALKLAND ISLANDS (MALVINAS)": "+500",
  "FIJI": "+679",
  "FINLAND": "+358",
  "FRANCE": "+33",
  "FRENCH GUIANA": "+594",
  "FRENCH POLYNESIA": "+689",
  "GABON": "+241",
  "GAMBIA": "+220",
  "GEORGIA": "+995",
  "GERMANY, FED REP OF": "+49",
  "GHANA": "+233",
  "GIBRALTAR": "+350",
  "GREECE": "+30",
  "GREENLAND": "+299",
  "GRENADA": "+1-473",
  "GUADELOUPE": "+590",
  "GUAM": "+1-671",
  "GUATEMALA": "+502",
  "GUERNSEY": "+44-1481",
  "GUINEA": "+224",
  "GUINEA-BISSAU": "+245",
  "GUYANA": "+592",
  "HAITI": "+509",
  "HONDURAS": "+504",
  "HONG KONG, CHINA": "+852",
  "HUNGARY": "+36",
  "ICELAND": "+354",
  "INDIA": "+91",
  "INDONESIA": "+62",
  "IRAN (ISLAMIC REP OF)": "+98",
  "IRAQ": "+964",
  "IRELAND": "+353",
  "ISLE OF MAN": "+44-1624",
  "ISRAEL": "+972",
  "ITALY": "+39",
  "JAMAICA": "+1-876",
  "JAPAN": "+81",
  "JERSEY": "+44-1534",
  "JORDAN": "+962",
  "KAZAKHSTAN": "+7",
  "KENYA": "+254",
  "KIRIBATI": "+686",
  "KOREA, DEM PEO REP OF": "+850",
  "KOREA, REP OF": "+82",
  "KUWAIT": "+965",
  "KYRGYZSTAN": "+996",
  "LAO PEO DEM REP": "+856",
  "LATVIA": "+371",
  "LEBANON": "+961",
  "LESOTHO": "+266",
  "LIBERIA": "+231",
  "LIBYAN ARAB JAMAHIRIYA": "+218",
  "LIECHTENSTEIN": "+423",
  "LITHUANIA": "+370",
  "LUXEMBOURG": "+352",
  "MACAU": "+853",
  "MACEDONIA": "+389",
  "MADAGASCAR": "+261",
  "MALAWI": "+265",
  "MALAYSIA": "+60",
  "MALDIVES REP OF": "+960",
  "MALI": "+223",
  "MALTA": "+356",
  "MARSHALL ISLANDS": "+692",
  "MARTINIQUE": "+596",
  "MAURITANIA": "+222",
  "MAURITIUS": "+230",
  "MAYOTTE": "+262",
  "MEXICO": "+52",
  "MICRONESIA": "+691",
  "MOLDOVA": "+373",
  "MONACO": "+377",
  "MONGOLIAN PEO REP": "+976",
  "MONTENEGRO": "+382",
  "MONTSERRAT": "+1-664",
  "MOROCCO": "+212",
  "MOZAMBIQUE": "+258",
  "MYANMAR": "+95",
  "NAMIBIA": "+264",
  "NAURU": "+674",
  "NEPAL": "+977",
  "NETHERLANDS": "+31",
  "NETHERLANDS ANTILLES": "+599",
  "NEW CALEDONIA": "+687",
  "NEW ZEALAND": "+64",
  "NICARAGUA": "+505",
  "NIGER": "+227",
  "NIGERIA": "+234",
  "NIUE": "+683",
  "NORFOLK ISLAND": "+672",
  "NORTHERN MARIANA ISLANDS": "+1-670",
  "NORWAY": "+47",
  "OMAN": "+968",
  "PAKISTAN": "+92",
  "PALAU": "+680",
  "PANAMA": "+507",
  "PAPUA NEW GUINEA": "+675",
  "PARAGUAY": "+595",
  "PERU": "+51",
  "PHILIPPINES": "+63",
  "PITCAIRN": "+64",
  "POLAND": "+48",
  "PORTUGAL": "+351",
  "PUERTO RICO": "+1-787",
  "QATAR": "+974",
  "REUNION": "+262",
  "ROMANIA": "+40",
  "RUSSIA": "+7",
  "RWANDA": "+250",
  "SAINT KITTS AND NEVIS": "+1-869",
  "SAINT VINCENT AND THE GRENADINES": "+1-784",
  "SAMOA": "+685",
  "SAN MARINO": "+378",
  "SAO TOME AND PRINCIPE": "+239",
  "SAUDI ARABIA": "+966",
  "SENEGAL": "+221",
  "SERBIA": "+381",
  "SEYCHELLES": "+248",
  "SIERRA LEONE": "+232",
  "SINGAPORE": "+65",
  "SLOVAK REPUBLIC": "+421",
  "SLOVENIA": "+386",
  "SOLOMON ISLANDS": "+677",
  "SOMALIA": "+252",
  "SOUTH AFRICA": "+27",
  "SOUTH SUDAN": "+211",
  "SPAIN": "+34",
  "SRI LANKA": "+94",
  "ST PIERRE ET MIQUELON": "+508",
  "ST. HELENA": "+290",
  "ST. LUCIA": "+1-758",
  "SUDAN": "+249",
  "SURINAM": "+597",
  "SWAZILAND": "+268",
  "SWEDEN": "+46",
  "SWITZERLAND": "+41",
  "SYRIAN ARAB REP": "+963",
  "TAIWAN": "+886",
  "TAJIKISTAN": "+992",
  "TANZANIA": "+255",
  "THAILAND": "+66",
  "TIMOR-LESTE": "+670",
  "TOGO": "+228",
  "TOKELAU": "+690",
  "TONGA": "+676",
  "TRINIDAD AND TOBAGO": "+1-868",
  "TUNISIA": "+216",
  "TURKEY": "+90",
  "TURKMENISTAN": "+993",
  "TURKS AND CAICOS ISLANDS": "+1-649",
  "TUVALU": "+688",
  "UGANDA": "+256",
  "UKRAINE": "+380",
  "UNITED ARAB EMIRATES": "+971",
  "UNITED KINGDOM": "+44",
  "UNITED STATES": "+1",
  "URUGUAY": "+598",
  "UZBEKISTAN": "+998",
  "VANUATU": "+678",
  "VATICAN CITY STATE (HOLY SEE)": "+379",
  "VENEZUELA": "+58",
  "VIETNAM SOC REP OF": "+84",
  "VIRGIN ISLANDS (US)": "+1-340",
  "WALLIS AND FUTUNA ISLANDS": "+681",
  "YEMEN": "+967",
  "ZAMBIA": "+260",
  "ZIMBABWE": "+263",
};

export const countryDigitLengths: Record<string, { min: number; max: number }> = {
  "AFGHANISTAN": { min: 9, max: 9 },
  "ALBANIA": { min: 9, max: 9 },
  "ALGERIA": { min: 9, max: 9 },
  "ARGENTINA": { min: 10, max: 10 },
  "AUSTRALIA": { min: 9, max: 9 },
  "AUSTRIA": { min: 10, max: 11 },
  "BAHRAIN": { min: 8, max: 8 },
  "BANGLADESH": { min: 10, max: 10 },
  "BELGIUM": { min: 9, max: 9 },
  "BRAZIL": { min: 10, max: 11 },
  "BRUNEI DARUSSALAM": { min: 7, max: 7 },
  "BULGARIA": { min: 9, max: 9 },
  "CAMBODIA": { min: 8, max: 9 },
  "CAMEROON": { min: 9, max: 9 },
  "CANADA": { min: 10, max: 10 },
  "CHILE": { min: 9, max: 9 },
  "CHINA PEO REP OF": { min: 11, max: 11 },
  "COLOMBIA": { min: 10, max: 10 },
  "CROATIA": { min: 9, max: 10 },
  "CUBA": { min: 8, max: 8 },
  "CYPRUS": { min: 8, max: 8 },
  "CZECH REPUBLIC": { min: 9, max: 9 },
  "DENMARK": { min: 8, max: 8 },
  "ECUADOR": { min: 9, max: 10 },
  "EGYPT": { min: 10, max: 10 },
  "ESTONIA": { min: 7, max: 8 },
  "ETHIOPIA": { min: 9, max: 9 },
  "FIJI": { min: 7, max: 7 },
  "FINLAND": { min: 9, max: 10 },
  "FRANCE": { min: 9, max: 9 },
  "GEORGIA": { min: 9, max: 9 },
  "GERMANY, FED REP OF": { min: 10, max: 11 },
  "GHANA": { min: 9, max: 10 },
  "GREECE": { min: 10, max: 10 },
  "HONG KONG, CHINA": { min: 8, max: 8 },
  "HUNGARY": { min: 9, max: 9 },
  "ICELAND": { min: 7, max: 7 },
  "INDIA": { min: 10, max: 10 },
  "INDONESIA": { min: 10, max: 12 },
  "IRAN (ISLAMIC REP OF)": { min: 10, max: 10 },
  "IRAQ": { min: 10, max: 10 },
  "IRELAND": { min: 9, max: 9 },
  "ISRAEL": { min: 9, max: 10 },
  "ITALY": { min: 10, max: 10 },
  "JAMAICA": { min: 7, max: 7 },
  "JAPAN": { min: 10, max: 11 },
  "JORDAN": { min: 9, max: 9 },
  "KAZAKHSTAN": { min: 10, max: 10 },
  "KENYA": { min: 9, max: 10 },
  "KOREA, REP OF": { min: 10, max: 11 },
  "KUWAIT": { min: 8, max: 8 },
  "LATVIA": { min: 8, max: 8 },
  "LEBANON": { min: 7, max: 8 },
  "LIBERIA": { min: 7, max: 8 },
  "LITHUANIA": { min: 8, max: 8 },
  "MACAU": { min: 8, max: 8 },
  "MALAYSIA": { min: 9, max: 10 },
  "MALDIVES REP OF": { min: 7, max: 7 },
  "MALTA": { min: 8, max: 8 },
  "MAURITIUS": { min: 8, max: 8 },
  "MEXICO": { min: 10, max: 10 },
  "MOROCCO": { min: 9, max: 9 },
  "MOZAMBIQUE": { min: 9, max: 9 },
  "MYANMAR": { min: 8, max: 10 },
  "NEPAL": { min: 10, max: 10 },
  "NETHERLANDS": { min: 9, max: 9 },
  "NEW ZEALAND": { min: 9, max: 10 },
  "NIGERIA": { min: 10, max: 11 },
  "NORWAY": { min: 8, max: 8 },
  "OMAN": { min: 8, max: 8 },
  "PAKISTAN": { min: 10, max: 10 },
  "PANAMA": { min: 8, max: 8 },
  "PAPUA NEW GUINEA": { min: 8, max: 8 },
  "PARAGUAY": { min: 9, max: 9 },
  "PERU": { min: 9, max: 9 },
  "PHILIPPINES": { min: 10, max: 10 },
  "POLAND": { min: 9, max: 9 },
  "PORTUGAL": { min: 9, max: 9 },
  "QATAR": { min: 8, max: 8 },
  "ROMANIA": { min: 10, max: 10 },
  "RUSSIA": { min: 10, max: 10 },
  "SAUDI ARABIA": { min: 9, max: 9 },
  "SENEGAL": { min: 9, max: 9 },
  "SERBIA": { min: 9, max: 10 },
  "SINGAPORE": { min: 8, max: 8 },
  "SLOVAK REPUBLIC": { min: 9, max: 9 },
  "SLOVENIA": { min: 8, max: 8 },
  "SOUTH AFRICA": { min: 9, max: 9 },
  "SPAIN": { min: 9, max: 9 },
  "SRI LANKA": { min: 9, max: 9 },
  "SWEDEN": { min: 9, max: 10 },
  "SWITZERLAND": { min: 9, max: 9 },
  "TAIWAN": { min: 9, max: 10 },
  "TANZANIA": { min: 9, max: 9 },
  "THAILAND": { min: 9, max: 9 },
  "TRINIDAD AND TOBAGO": { min: 7, max: 7 },
  "TUNISIA": { min: 8, max: 8 },
  "TURKEY": { min: 10, max: 10 },
  "UGANDA": { min: 9, max: 9 },
  "UKRAINE": { min: 9, max: 9 },
  "UNITED ARAB EMIRATES": { min: 9, max: 9 },
  "UNITED KINGDOM": { min: 10, max: 10 },
  "UNITED STATES": { min: 10, max: 10 },
  "URUGUAY": { min: 8, max: 8 },
  "UZBEKISTAN": { min: 9, max: 9 },
  "VENEZUELA": { min: 10, max: 10 },
  "VIETNAM SOC REP OF": { min: 9, max: 10 },
  "YEMEN": { min: 9, max: 9 },
  "ZAMBIA": { min: 9, max: 9 },
  "ZIMBABWE": { min: 9, max: 9 },
};

const DEFAULT_DIGIT_RANGE = { min: 7, max: 15 };

const allDialingCodes = Array.from(new Set(Object.values(countryDialingCodes))).sort((a, b) => b.length - a.length);

export function getDialingCode(countryName: string): string | undefined {
  return countryDialingCodes[countryName.toUpperCase()];
}

export function getDigitRange(countryName: string): { min: number; max: number } {
  return countryDigitLengths[countryName.toUpperCase()] || DEFAULT_DIGIT_RANGE;
}

export function stripDialingCode(mobile: string): string {
  const trimmed = mobile.trim();
  for (const code of allDialingCodes) {
    if (trimmed.startsWith(code)) {
      return trimmed.slice(code.length).replace(/^[\s-]+/, '');
    }
  }
  return trimmed;
}

export function applyDialingCode(countryName: string, currentMobile: string): string {
  const code = getDialingCode(countryName);
  if (!code) return currentMobile;
  const digits = stripDialingCode(currentMobile);
  return digits ? `${code} ${digits}` : code;
}

export function extractLocalDigits(countryName: string, mobile: string): string {
  const code = getDialingCode(countryName);
  if (!code) return mobile.replace(/\D/g, '');
  const stripped = stripDialingCode(mobile);
  return stripped.replace(/\D/g, '');
}

export function normalizeMobileInput(countryName: string, rawInput: string): string {
  const code = getDialingCode(countryName);
  if (!code) return rawInput;
  if (rawInput.length <= code.length) {
    return code;
  }
  const afterCode = rawInput.slice(code.length).replace(/^[\s-]+/, '');
  const localDigits = afterCode.replace(/\D/g, '');
  return localDigits ? `${code} ${localDigits}` : code;
}

export function validateMobileNumber(countryName: string, mobile: string): string | null {
  if (!countryName || !mobile) return null;

  const code = getDialingCode(countryName);
  if (!code) return null;

  const localDigits = extractLocalDigits(countryName, mobile);
  if (!localDigits) return null;

  const range = getDigitRange(countryName);

  if (localDigits.length < range.min || localDigits.length > range.max) {
    if (range.min === range.max) {
      return `Mobile number must be exactly ${range.min} digits after ${code}.`;
    }
    return `Mobile number must be ${range.min}–${range.max} digits after ${code}.`;
  }

  return null;
}
