import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FormattedDateInput } from "@/components/ui/formatted-date-input";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { usePermissions } from "@/contexts/PermissionsContext";
import { sailDesignSystem, getButtonClasses } from "@/config/sailDesignSystem";
import { registerFixedParts } from "@/components/configured-form/fixedPartRegistry";

export type DebriefingFixedData = { partA?: any; partC?: any };
export const readDebriefingValue = (value: unknown): string => value === null || value === undefined || value === "" ? "—" : String(value);
export const formatDebriefingDate = (value: unknown): string => { if (!value) return "—"; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }).replace(/ /g, "-"); };
export const debriefingModeLabel = (value: unknown): string => ({ company_office: "Company Office", manning_agent: "Manning Agent's Office", video_call: "Video Call" } as Record<string, string>)[String(value)] || readDebriefingValue(value);
export const buildDebriefingPartAPayload = (date: string, mode: string) => ({ debriefingDate: date || null, modeOfDebriefing: mode || null });
export const buildDebriefingPartCPayload = (comments: string) => ({ officeReviewComments: comments || null });
const tokens = sailDesignSystem.colors; const buttonClasses = getButtonClasses();
const cardStyle = { backgroundColor: tokens.cardBackground, borderColor: tokens.border, borderRadius: sailDesignSystem.components.card.borderRadius, boxShadow: sailDesignSystem.components.card.shadow }; const sectionStyle = { backgroundColor: tokens.tableHeader, borderColor: tokens.border }; const labelStyle = { color: tokens.textSecondary, fontSize: sailDesignSystem.typography.fontSize.xs }; const valueStyle = { color: tokens.textPrimary, fontSize: sailDesignSystem.typography.fontSize.sm };
function Header({ part, subtitle, completed }: { part: "A" | "C"; subtitle: string; completed: boolean }) { return <header className="mb-6 border-b pb-4" style={{ borderColor: tokens.headerText }}><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold" style={{ color: tokens.headerText }}>Part {part}: {part === "A" ? "Basic Information" : "Office Review"}</h2><p className="mt-1 text-sm" style={{ color: tokens.textSecondary }}>{subtitle}</p></div>{completed && <span className="text-xs font-semibold" style={{ color: tokens.success }}>Completed</span>}</div><div className="mt-3 h-0.5 w-full" style={{ backgroundColor: tokens.headerText }} /></header>; }
function Field({ label, value }: { label: string; value: unknown }) { return <div className="rounded-md border px-3 py-2" style={sectionStyle}><label className="block font-medium" style={labelStyle}>{label}</label><p className="mt-1" style={valueStyle}>{readDebriefingValue(value)}</p></div>; }
export function DebriefingPartA({ submissionUuid, data, completed, onSaved, readOnly = false }: { submissionUuid: string; data?: any; completed: boolean; onSaved?: () => void; readOnly?: boolean }) {
  const [record, setRecord] = useState(data); const [draft, setDraft] = useState({ date: data?.debriefing_date || "", mode: data?.mode_of_debriefing || "" }); const [saving, setSaving] = useState(false); const { toast } = useToast();
  useEffect(() => setRecord(data), [data]); useEffect(() => setDraft({ date: record?.debriefing_date || "", mode: record?.mode_of_debriefing || "" }), [record]);
  const save = async () => { setSaving(true); try { await apiRequest("PUT", `/api/v2/debriefings/submissions/${submissionUuid}/part-a`, buildDebriefingPartAPayload(draft.date, draft.mode)); onSaved?.(); toast({ title: "Part A saved", description: "The debriefing date and mode have been recorded." }); } catch (error) { toast({ title: "Part A could not be saved", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setSaving(false); } };
  const fields: [string, unknown][] = [["Crew member", record?.seafarer_name], ["Nationality", record?.nationality], ["Vessel", record?.vessel_name], ["Rank Served", record?.rank_served], ["Date Signed On", formatDebriefingDate(record?.sign_on_date)], ["Date Signed Off", formatDebriefingDate(record?.sign_off_date)], ["Reason for Sign Off", record?.reason_for_sign_off]];
  return <section className="rounded-lg border p-6" style={cardStyle} data-testid="debriefing-part-a"><Header part="A" subtitle="Source details are read-only; complete the debriefing record below." completed={completed}/><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, value]) => <Field key={label} label={label} value={value}/>)}<label className="block font-medium" style={labelStyle}>Debriefing Date{completed && !readOnly ? <div className="mt-1 rounded-md border px-3 py-2" style={{ ...sectionStyle, ...valueStyle }}>{formatDebriefingDate(draft.date)}</div> : <FormattedDateInput value={draft.date} disabled={readOnly} onChange={e => setDraft(v => ({ ...v, date: e.target.value }))} className="mt-1" data-testid="input-debriefing-date"/>}</label><label className="block font-medium" style={labelStyle}>Mode of Debriefing<Select disabled={completed || readOnly} value={draft.mode} onValueChange={mode => setDraft(v => ({ ...v, mode }))}><SelectTrigger className="mt-1"><SelectValue placeholder="Select mode"/></SelectTrigger><SelectContent><SelectItem value="company_office">Company Office</SelectItem><SelectItem value="manning_agent">Manning Agent's Office</SelectItem><SelectItem value="video_call">Video Call</SelectItem></SelectContent></Select></label></div>{!completed && !readOnly && <div className="mt-6 flex justify-end"><Button size="sm" className={buttonClasses.primary} onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save Part A"}</Button></div>}</section>;
}
export function DebriefingPartC({ submissionUuid, data, completed, onSaved, readOnly = false }: { submissionUuid: string; data?: any; completed: boolean; onSaved?: () => void; readOnly?: boolean }) {
  const { userType } = usePermissions(); const [record, setRecord] = useState(data); const [comments, setComments] = useState(data?.office_review_comments || ""); const [saving, setSaving] = useState(false); const { toast } = useToast(); useEffect(() => setRecord(data), [data]); useEffect(() => setComments(record?.office_review_comments || ""), [record]); if (!readOnly && userType?.toLowerCase() !== "office") return null;
  const save = async () => { setSaving(true); try { await apiRequest("PUT", `/api/v2/debriefings/submissions/${submissionUuid}/part-c`, buildDebriefingPartCPayload(comments)); onSaved?.(); toast({ title: "Office review saved", description: "The reviewer details have been recorded." }); } catch (error) { toast({ title: "Office review could not be saved", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setSaving(false); } };
  return <section className="rounded-lg border p-6" style={cardStyle} data-testid="debriefing-part-c"><Header part="C" subtitle="Internal review record" completed={completed}/><div className="rounded-md border p-4" style={sectionStyle}><Textarea disabled={completed || readOnly} value={comments} onChange={e => setComments(e.target.value)} placeholder="Add reviewer comments…" rows={5} className="bg-transparent"/></div><div className="mt-4 flex items-center justify-between gap-4 text-xs" style={{ color: tokens.textSecondary }}><span>{record?.office_reviewed_by_name ? `Reviewed by ${record.office_reviewed_by_name}` : "Not yet reviewed"}{record?.office_reviewed_at ? ` · ${formatDebriefingDate(record.office_reviewed_at)}` : ""}</span>{!completed && !readOnly && <Button size="sm" className={buttonClasses.primary} onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save review"}</Button>}</div></section>;
}
export function debriefingFixedParts(submissionUuid: string, data: DebriefingFixedData, completed: boolean, onSaved: () => void, readOnly = false): Record<string, React.ReactNode> { return { A: <DebriefingPartA submissionUuid={submissionUuid} data={data.partA} completed={completed} onSaved={onSaved} readOnly={readOnly}/>, C: <DebriefingPartC submissionUuid={submissionUuid} data={data.partC} completed={completed} onSaved={onSaved} readOnly={readOnly}/> }; }

registerFixedParts("debriefing", ({ readOnly }) => debriefingFixedParts("", {}, false, () => undefined, readOnly));